"""
    to run on compute server replace raxml-ng with ./raxml-ng
    or add current directory to path
        PATH=$PATH:.
"""

"""
generates estimates of the melanogaster branch at SNP positions
for DM6 reference
only works for two-base SNPs

takes as input a chromosome number
generates two files:
    a csv file with results
    a txt file with problems 

uses the idea described in  ancetral_base_probabilities.nb

expects the following directory structure 
. current directory
./ancestral  (where the .csv and problems.txt files end up)
./maf   (.maf and .maf.gz files generated by cactus or downloaded from somewhere)
./tempwork  (holds results of raxml runs)


"""
from types import MappingProxyType
import bx.align.maf as bxmaf
import pickle
import sys
import os.path as op
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.SeqUtils import GC
import math
import csv 
import subprocess
import argparse
import os
import pickle
import glob
import bisect
import platform
   
def binary_search(a, x): 
    """
        for checking presnce of x in a long list a
    """
    i = bisect.bisect_left(a, x) 
    if i != len(a) and a[i] == x: 
        return True 
    else: 
        return False

def ID_snps_in_block(mmap,snplist,seq,start,size):
    """
        mmap is a dictionary in which the keys are 0-based positions in the melanogaster sequence
        in the mfa block and the values are positions in Dm6
        snplist is a list of snps in the current chromosome
        seq is the melanogaster sequence in a block 
        start is a 0-based position at the beginning of the sequence that comes from the maf file 

        return a dictionary with 0-based positions in the sequence as keys and the 1-based genome snp position as values

        use binary_search for rapid check of whether or not a position is in a list 

    """
    sd = {}
    j = 1
    for i,b  in enumerate(seq):
        if b != '-':
            gbase = mmap[i]
            if binary_search(snplist,gbase):
                sd[i] = gbase
            gbase += 1
    return sd


def addancnums(focalstr,treestr):
    """
        add internal node values to the treestring
        for the focalstr (e.g. 'D_melanogaster') use a value of 0 
        when the node value base estimates are gotten from the raxml output
        the '0' gets used 
    """
    fi = treestr.find(focalstr) + len(focalstr)
    treel = list(treestr)
    ppos = [i+1 for i, x in enumerate(treel) if x == ')']
    i  = fi
    cp = 0
    while True:
        cp -=  treel[i] == '('
        cp +=  treel[i] == ')'
        if cp == 1:
            break
        i += 1
    fi = i+1
    assert fi in ppos
    ppos.reverse()
    for i in range(len(ppos)):
        if ppos[i] ==fi:
            nodeval = str(0)
        else:
            nodeval = str(i+1)
        treel.insert(ppos[i],nodeval)
    newtreestr= ''.join(treel)
    return newtreestr

def getresultslist(partialresultslist,ancaltprobfile,pf,mafn,blocknum,ac,mapundtoref,mapreftound):
    """
    partialresultslist,ancaltprobfile,pf,mafn,bi,align.components[hsindex],mapundtoref,mapreftound
        now only work with ancaltprobfile
        # partialresults is a list with length equal to the text length for sequences in the block
        # ancrefprobfile is the file for the reference sequence from the current block
        # ancaltprobfile is the file for the sequence with alternate alleles swapped in for the current block
        # mapundtoref is a dictionary with positions in the alignment built by raxml that does not include 
        #     undetermined sites, the values are the positions in the original text 
            
        #     mapundtoref[i] holds the position in the full sequence that corresponds to 
        #     position i in the pruned (no undetermined positions) sequence 
        
        # mapreftound is a dictionary with positions in the original text and values that are positions in the 
        #     alignment built by raxml that does not included undetermined positions

        #     mapreftound[j] holds the position in the pruned sequence that corresponds to
        #     position j in the full sequence     

  
    """
    results = []
    bases = ['A','C','G','T']
    try:
        altlines = open(ancaltprobfile,'r').readlines()
        for i,line in enumerate(altlines):
            if line[0] == '0': # human ancestral node
                alti  = i
                break
        for ui in mapreftound:
            ri = mapreftound[ui]  # corresponding position in the original text
            row = partialresultslist[ui]
            if row != [] :
                altls = list(map(float,altlines[ri+alti].split()[3:])) # probabilities given alt allele
                basecall = bases[altls.index(max(altls))]
                newrow = row + altls + [basecall]

                results.append(newrow)
    except:
        errorinfo = "Error: {}  details:  {} line#: {} ".format(sys.exc_info()[0],sys.exc_info()[1], sys.exc_info()[2].tb_lineno)
        print(errorinfo)
        tempstr = "CALCULATING ANCESTOR PROBABILTY PROBLEM TRY FAIL '{}' in block {} file {} startpos {} sequencelength {}\n".format(errorinfo,blocknum,mafn,ac.start,len(ac.text))
        pf.write(tempstr)
    return results


def getmafnames(mafdir):
    """
        returns a list of maf filenames
    """
    mafnames = glob.glob(op.join(mafdir,"*.maf.gz"))
    mafnamesnogz= glob.glob(op.join(mafdir,"*.maf"))
    mafnames = mafnames + mafnamesnogz
    return mafnames

def getalttext_set_snp_missing(mmap,text,snpdic,posdic,chrstr):
    """
        generate an alternate sequence in which base positions where snps are located are replaced with '-'
        
    """
    partialresults = []
    bases = ['A','C','G','T']
    text = list(text.upper())
    snpintxt = False
    for i,b  in enumerate(text):
        if b != '-':
            if i in snpdic:
                if text[i].upper() != posdic[snpdic[i]][0]:
                    ## text should be the melanogaster reference and should match the ref column from the vcf file in posdic
                    print("HALT",asserterror,text[i].upper(),posdic[snpdic[i]][0])
                    exit()
                text[i] = '-'
                partialresults.append([chrstr,snpdic[i], posdic[snpdic[i]][0],posdic[snpdic[i]][1]])
                snpintxt = True
            else:
                partialresults.append([])
        else:
            partialresults.append([])
    return snpintxt, ''.join(text),partialresults

def opencloseresultsfile(rf,dmelcsvfn):
    """
        save and reopen the file in append mode 
    """
    rf.close()
    rf = open(dmelcsvfn,'a')
    rw = csv.writer(rf, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)   
    return rf,rw


def opencloseprobfile(pf,problemsfn):
    """
        save and reopen the file in append mode 
    """    
    pf.close()
    pf = open(problemsfn,'a')
    return pf

def idallgaps(fastareffn):
    """
        generate a list of positions where all of the sequences have a gap symbol
    """
    srs = [sr for sr in SeqIO.parse(fastareffn,'fasta')]
    indels = set(i for i, x in enumerate(list(srs[0].seq)) if x == "-")
    for sr in srs[1:]:
        removeset = set()
        for nd in indels:
            if sr.seq[nd] != '-':
                removeset.add(nd)
        indels.difference_update(removeset)
        if len(indels) == 0:
            break
    allindels = list(indels)
    allindels.sort()
    return allindels
        

def getundmatp(pf,workdir,fastareffn,reducedphyfn):
    """
        generate dictionaries that map between the original ref sequence in the maf file
        and the sequence generated by raxml which is based on removing undetermined positions 

        fastareffn is the name of existing file that holds the original sequences
        
        To build these it is necessary to open the raxml phylip format file, make a fasta file
            then open the fasta file and get the sequence 

        returns mapundtoref and mapreftound

        mapundtoref[i] holds the position in the full sequence that corresponds to 
        position i in the pruned (no undetermined positions) sequence 
        
        mapreftound[j] holds the position in the pruned sequence that corresponds to
        position j in the full sequence 

        pf is the problem file
    """
    #get original sequence
    allindels = idallgaps(fastareffn) # holds positions that are not present in reducedphyfn
    try:
        sp = SeqIO.parse(fastareffn,'fasta')
        ref = next(sp)
        assert ref.description == "D_melanogaster"
        refseq =str(ref.seq).upper()
        assert refseq.count('N') == 0
        olen = len(refseq)
        # make a fasta file out of the raxml alignment file 
        if op.exists(reducedphyfn):
            f = open(reducedphyfn,'r')
            # fw = open(reducedfastafn,'w')
            line = f.readline().strip().split()
            [nseqs,seqlen] = list(map(int,line))
            while True:
                [speciesname, undseq] = f.readline().strip().split()
                if speciesname == "D_melanogaster":
                    break
            assert seqlen + len(allindels) == olen
        else:
            undseq = refseq
        ri = ui = 0
        mapundtoref = {}
        while True:
            if ui in allindels:
                ui += 1
            else:
                mapundtoref[ri] = ui
                ri += 1
                ui += 1
            if ui >= olen:
                break
        mapreftound = dict((v,k) for k,v in mapundtoref.items())
    except:
        errorinfo = "Error: {}  details:  {} line#: {} ".format(sys.exc_info()[0],sys.exc_info()[1], sys.exc_info()[2].tb_lineno)
        print(errorinfo)
        tempstr = "GETUNDMATP PROBLEM TRY FAIL '{}' fastareffn {} reducedphyfn {}\n".format(errorinfo,fastareffn,reducedphyfn)
        pf.write(tempstr)
    return mapundtoref,mapreftound

def dm6map(seq,start,size):
    """
        gmap is a dictionary, keys are 1-based positions in Dm6
        values are 1-based positions in the melanogaster sequence in the mfa block 
        positions that were gaps in the human sequence are not mapped
        mmap is a dictionary in which the keys are positions in the melanogaster sequence
        in the mfa block and the values are positions in Dm6
    """
    gmap ={}
    mmap = {}
    gbase = start+1  #start is 0-based, gbase is 1-based
    j = 1
    for i,b  in enumerate(seq):
        if b != '-':
            gmap[gbase] = i+1
            mmap[i] = gbase
            gbase += 1
    assert len(gmap) == size
    assert len(mmap) == size
    return gmap,mmap


def runit(chrstr):
    """
    go thru maf files one by one
    gzip -d the fileif needed
    go through the blocks in order
        for each block (if there are three or more sequences)
            get the melanogaster sequence
            build a mapping of the dmel base  numbering to the position in the block 
            build fasta file and run raxml to get the tree string
            add node numbers to the tree string,  setting 0 to the ancestor of human
            get the mapping of bases from the reduced raxml input to the original 
            run raxml using the tree string and the --ancestral option to get the base probabilities
            pull out the base alignment numbers and probabilities
            map the alignment numbers to the deml ref numbers
            write the base probabilities with the dmel numbers

    """
    specieslist = ["D_erecta","D_mauritiana","D_melanogaster","D_santomea","D_sechellia","D_simulans","D_yakuba"]
    mafdir = r"./maf"
    workdir = r"./tempwork"
    resultsdir = r"./ancestral"
    mafnamelist = getmafnames(mafdir)
    pckg = pickle.load(open("Dmelgroup_snp.p","rb"))
    snplists = pckg[0]
    allposdic = pckg[1]
    fastaaltfn = "tempalt" + chrstr + ".fasta"
    fastaaltfn = op.join(workdir,fastaaltfn)
    if "Windows" in platform.system():
        raxcmd = "raxml-ng"
    else:        
        if "SMP" in platform.version():
            raxcmd = "./raxml-ng"
        else:
            raxcmd = "raxml-ng"


    
    headers = ["Chr","Dmel6pos1based","ref","alt","probA","probC","progG","probT","EstimatedAncest"]

    blockcount = 0
    opencloseinterval = 2
    dmelcsvfn = op.join(resultsdir,"D_melanogaster_ancbase_" +chrstr + ".csv")
    problemsfn  = op.join(resultsdir,"D_melanogaster_ancbase_problems_" + chrstr + ".txt")
    pf = open(problemsfn,'w')
    rf = open( dmelcsvfn,'w')
    rw = csv.writer(rf, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    rw.writerow(headers)
    for mafn in mafnamelist:
        checkchrstr = mafn[mafn.rfind("_")+1:][:-4]
        if checkchrstr == chrstr:
            print("file:",mafn)
            chrstr = mafn[mafn.rfind("_")+1:][:-4]
            snplist = snplists[chrstr]
            posdic = allposdic[chrstr]
            checkroot = []
            snplist.sort()
            if mafn[-3:] == ".gz" :
                cmdlist = ['gzip','-d',mafn]
                subprocess.call(cmdlist,stdout = subprocess.PIPE,stderr = subprocess.STDOUT)
                mafn = mafn[:-3] # maf name without the .gz
            mafreader = bxmaf.Reader(open(mafn,'r'))
            results=[]
            # print("block ",end='')
            bi = 0
            for align in mafreader:
                if len(align.components) >= 5:
                    # print(bi,' ',end='')
                    blockcount += 1
                    bi += 1
                    labels =[x.src[:x.src.find(".")] for x in align.components]
                    if labels.count("D_melanogaster") == 1:
                        hsindex = labels.index("D_melanogaster")
                        gmap,mmap = dm6map(align.components[hsindex].text,align.components[hsindex].start,align.components[hsindex].size)
                        snpdic = ID_snps_in_block(mmap,snplist,align.components[hsindex].text,align.components[hsindex].start,align.components[hsindex].size)
                        faltf = open(fastaaltfn,'w')
                        numspecies = 0
                        textok = True
                        snpintxt = False
                        lentext = 0
                        othersrs = []
                        speciescounts = [0 for s in specieslist]
                        try:
                            for alignrecord in align.components:
                                if "Anc" not in alignrecord.src:
                                    species  =  alignrecord.src[:alignrecord.src.find('.')]
                                    if speciescounts[specieslist.index(species)] > 0:
                                        speciesstr = species + str(speciescounts[specieslist.index(species)])
                                    else:
                                        speciesstr = species
                                    speciescounts[specieslist.index(species)] += 1
                                    if species == "D_melanogaster":
                                        snpintxt,alttext,partialresultslist = getalttext_set_snp_missing(mmap,alignrecord.text,snpdic,posdic,chrstr)
                                        dmsr = SeqRecord(seq=Seq(alttext.upper()),id=speciesstr, description='')
                                        lentext = len(alttext)
                                        textok = textok and snpintxt 
                                    else:
                                        othersrs.append(SeqRecord(seq=Seq(alignrecord.text.upper()),id=speciesstr, description=''))
                                    
                                    numspecies += 1
                            textok = textok and lentext > numspecies
                            SeqIO.write(dmsr,faltf,"fasta")
                            for sr in othersrs:
                                SeqIO.write(sr,faltf,"fasta")
                        except:
                            errorinfo = "Error: {}  details:  {} line#: {} ".format(sys.exc_info()[0],sys.exc_info()[1], sys.exc_info()[2].tb_lineno)
                            print(errorinfo)
                            tempstr = "SeqIO LOOP PROBLEM TRY FAIL '{}' in block {} file {}\n".format(errorinfo,bi,mafn)
                            pf.write(tempstr)
                            textok = False
                        faltf.close()
                        if textok and numspecies > 2:
                            raxmlprefixes = ["treerun_" + chrstr,"rootrun_" + chrstr]
                            try:
                                reducedphyfn = op.join(workdir,raxmlprefixes[0]+".raxml.reduced.phy")
                                if op.exists(reducedphyfn):
                                    os.remove(reducedphyfn)
                                ancaltprobfile = op.join(workdir,raxmlprefixes[1] + ".raxml.ancestralProbs")
                                if op.exists(ancaltprobfile):
                                    os.remove(ancaltprobfile)
                                cmdlist = [raxcmd,"--msa",fastaaltfn,"--msa-format","FASTA","--prefix",op.join(workdir,raxmlprefixes[0]),"--model","GTR+G","--threads","1","--seed","123","--redo"]
                                pp = subprocess.Popen(cmdlist,stdout = subprocess.PIPE,stderr = subprocess.STDOUT)
                                stdoutdata, stderrdata = pp.communicate()
                                besttreefn = op.join(workdir,raxmlprefixes[0] +".raxml.bestTree")
                                rax1ok =  op.exists(besttreefn)
                                if rax1ok:
                                    treestr = open(besttreefn,"r").readline().strip()
                                    newtreestr = addancnums("D_melanogaster",treestr)
                                    mapundtoref,mapreftound = getundmatp(pf,workdir,fastaaltfn,reducedphyfn)
                                    raxnewtreefn = op.join(workdir,raxmlprefixes[0] + "newtree")
                                    f = open(raxnewtreefn,'w')
                                    f.write(newtreestr + "\n")
                                    f.close()
                                    cmdlist = [raxcmd,"--msa",fastaaltfn,"--msa-format","FASTA","--prefix",op.join(workdir,raxmlprefixes[1]),"--model","GTR+G","--tree",raxnewtreefn,"--ancestral","--threads","1","--seed","123","--redo"]
                                    subprocess.call(cmdlist,stdout = subprocess.PIPE,stderr = subprocess.STDOUT)
                                
                            except:
                                errorinfo = "Error: {}  details:  {} line#: {} ".format(sys.exc_info()[0],sys.exc_info()[1], sys.exc_info()[2].tb_lineno)
                                print(errorinfo)
                                tempstr = "RAXML PROBLEM TRY FAIL '{}' in block {} file {} startpos {}\n".format(errorinfo,bi,mafn,align.components[hsindex].start)
                                pf.write(tempstr)
                                rax1ok = False
                                pass
                            try:
                                if rax1ok:
                                    resultslist = getresultslist(partialresultslist,ancaltprobfile,pf,mafn,bi,align.components[hsindex],mapundtoref,mapreftound)
                                    for row in resultslist:
                                        assert row[1] not in checkroot
                                        checkroot.append(row[1])
                                        rw.writerow(row)
                            except:
                                errorinfo = "Error: {}  details:  {} line#: {} ".format(sys.exc_info()[0],sys.exc_info()[1], sys.exc_info()[2].tb_lineno)
                                print(errorinfo)
                                tempstr = "results fail '{}' in block {} file {} startpos {}\n".format(errorinfo,bi,mafn,align.components[hsindex].start)
                                pf.write(tempstr)
                                pass                                           
                        else:
                            if numspecies <= 2:
                                tempstr = "TOO FEW SPECIES in block {} file {} startpos {} sequencelength {}\n".format(bi,mafn,align.components[hsindex].start,len(align.components[hsindex].text))
                                pf.write(tempstr)    
                            if textok == False:
                                tempstr = "textok is false in block {} file {} startpos {} sequencelength {}\n".format(bi,mafn,align.components[hsindex].start,len(align.components[hsindex].text))
                                pf.write(tempstr)    

                    else:
                        pf.write("Multiple D_melanogaster seqs PROBLEM in block in block {} file {}\n".format(bi,mafn))                
                        for li,label in enumerate(labels):
                            if label == "D_melanogaster":
                                tempstr = "   chr {} pos {} sequencelength {}\n".format(chrstr, align.components[li].start,len(align.components[li].text))
                                pf.write(tempstr)
                    if blockcount % opencloseinterval ==0: # write a batch of results 
                        rf,rw = opencloseresultsfile(rf,dmelcsvfn)
                        pf = opencloseprobfile(pf,problemsfn)
            
            rf.close()
            pf.close()
            missingsnps = list(set(snplist) - set(checkroot))
            missingsnps.sort()
            print("chr {}  #snps found and resolve: {}  #snps not found or resolved".format(chrstr,len(checkroot),len(missingsnps)))
            missingsnpsfn  = op.join(resultsdir,"D_melanogaster_ancbase_missingsnps_" + chrstr + ".txt")
            mf = open(missingsnpsfn,'w')
            mf.write("Chromosome {} SNPs not found or resolved in maf file (total:{})\n".format(chrstr,len(missingsnps)))
            for i in missingsnps:
                mf.write("{}\n".format(i))
            mf.close()

runit(sys.argv[1])

    